# Generated by Django 2.1.5 on 2019-08-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Estado')),
                ('image', models.ImageField(upload_to='estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha del Evento')),
                ('hora', models.TimeField(verbose_name='Hora del Evento')),
                ('km', models.CharField(blank=True, max_length=12, null=True, verbose_name='Kilómetros de recorrido')),
                ('time', models.TimeField(verbose_name='Tiempo de recorrido')),
                ('punto_inicio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Punto de inicio')),
                ('costo', models.FloatField(verbose_name='Costo')),
                ('imagen', models.ImageField(upload_to='evento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Estados', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created'],
            },
        ),
    ]
