# Generated by Django 2.1.5 on 2019-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2019-08-17', verbose_name='Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estados',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default='2019-08-17', verbose_name='Modificado'),
            preserve_default=False,
        ),
    ]
