# Generated by Django 2.1.5 on 2019-08-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190818_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Estados', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='km',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kilómetros de recorrido'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='punto_inicio',
            field=models.CharField(max_length=50, verbose_name='Punto de inicio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='time',
            field=models.CharField(max_length=70, verbose_name='Tiempo de recorrido'),
        ),
    ]
